M48
; DRILL file {KiCad (7.0.0)} date Wed Aug 23 12:35:51 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-23T12:35:51+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0402
%
G90
G05
T1
X10.1119Y-4.3649
X10.1419Y-2.9053
X10.3481Y-4.3649
X10.3781Y-2.9053
T0
M30
